### ISSUE TITLE
Dexrius Bugs

### ISSUE THREAD

**Issue by Dmgctrltankadin** [HorseyStudios/Dexrius#1]
The back button does not display the Reset/Quit menu. Currently the only way to get out of the program is to press your finger at the to of the screen to access your notifications. This enables you to have the Back, Home, Reset buttons to come up. Press the Home or Resent Programs buttons to exit. A related point. To completely reset the game, you have to go to Resent Programs and manually close the app.

**Comment by portal17** [comment]
Yes, once we have a main menu set up you can close the app by pressing Quit or the Back button

**Comment by Dmgctrltankadin** [comment]
I figured as much. ephrisian just wanted me to log the bug. :)

**Comment by portal17** [comment]
Cool. Thanks!
